language: node_js
cache: yarn
branches:
  only:
    - master
notifications:
  email: false
script:
  - yarn lint
  - yarn test
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
after_success:
  - yarn travis-deploy-once "npm run semantic-release"
